### ISSUE TITLE
Don't duplicate <url>

### ISSUE THREAD

**Issue by alkisg** [cpuguy83/go-md2man#79] opened 2022-01-08 07:04 UTC
With this input:

```
<https://ltsp.org>
```

this output is produced:

```
https://ltsp.org
\[la]https://ltsp.org\[ra]
```

That would make sense for the `[text](url)` syntax, but it doesn't make sense for the `<url>` syntax where the text is the link itself. There's no need to see it twice.

Ronn produces this instead:

```
\fIhttps://ltsp\.org\fR
```

Pandoc produces this instead:

```
<https://ltsp.org>
```

Both of them are acceptable. Thank you!

**Comment by wsakernel** [comment] 2024-02-03 06:32
Yes, I hit the same issue. Mostly with mailto-links:

    John Doe <john@doe.org>

becomes

    John Doe john@doe.org
    \[la]mailto:john@doe.org\[ra]

I work around it by encapsulating it with backticks, yet I'd actually prefer the pandoc-style output which looks like the source.

But in general, this is a cool program. Especially for small projects which want to avoid pandoc as a build-dependency. Thanks!

**Comment by cpuguy83** [comment] 2024-02-05 04:38
The original case of this is resolved in 66e0792f4bf72fede875e62279870032025ba094

**Comment by cpuguy83** [comment] 2024-02-05 05:12
I was looking into your case @wsakernel but I'm not sure.
I think this is working as intended since it is using the markdown autolink tags.
I could special case it where if the test contains the link we don't need to render the link but even then it would require special casing `mailto` links.
It's not hard to do it just doesn't feel right.

**Comment by cpuguy83** [comment] 2024-02-05 05:15
I'm going to close this for now since the original issue was resolved.
I could probably be convinced on the new case for mailto links, but that's really a separate issue.

**Closed by cpuguy83** 2024-02-05 05:15 UTC

**Comment by wsakernel** [comment] 2024-02-05 11:05
Okay, I thought '<' and '>' (autolinks) are an optional markdown extension. But if they are considered regular markdown syntax, then your reasoning makes sense. In that case, my workaround with the backticks is actually one way to handle it IMO. Thanks for looking into it!
